// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $character_id_ from "./routes/character/[id].tsx";
import * as $characters_page_ from "./routes/characters/[page].tsx";
import * as $fails_search from "./routes/fails/search.tsx";
import * as $index from "./routes/index.tsx";
import * as $people_index from "./routes/people/index.tsx";
import * as $search_index from "./routes/search/index.tsx";
import * as $starships_index from "./routes/starships/index.tsx";
import * as $starshipsfail_index from "./routes/starshipsfail/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/character/[id].tsx": $character_id_,
    "./routes/characters/[page].tsx": $characters_page_,
    "./routes/fails/search.tsx": $fails_search,
    "./routes/index.tsx": $index,
    "./routes/people/index.tsx": $people_index,
    "./routes/search/index.tsx": $search_index,
    "./routes/starships/index.tsx": $starships_index,
    "./routes/starshipsfail/index.tsx": $starshipsfail_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
